# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses. This specifies the base container image.
type: 'python:3.12'  # Adjust based on the version you wish to use

# Define writable directories. Adjust according to your application's needs.
mounts:
  '/tmp':  # Flask typically uses /tmp for temporary file storage
    source: local
    source_path: tmp

# The size of the persistent disk of the application (in MB).
disk: 2048

hooks:
    # Commands to run during the build process
    build: |
      pip install -r requirements.txt  # Adjust if you're using pipenv or another package manager

web:
  # Command to start your Flask application
  commands: 
    start: "flask run --host=0.0.0.0 --port=$PORT"

# Environment variables (if needed)
variables:
    python:
      FLASK_ENV: 'production'  # Ensures Flask runs in production mode
