name: app
type: python:3.9  # Adjust the Python version as necessary
build:
    flavor: none
hooks:
    build: |
      pip install -r requirements.txt  # Install dependencies
relationships:
    database: "mysqldb:mysql"  # Define the relationship to a MySQL service, if needed
disk: 1024  # Disk size in MB
web:
    commands:
        start: "flask run --host=0.0.0.0 --port=$PORT"
runtime:
    extensions:
        - pdo_mysql  # Example, adjust according to your needs
